In [1]:
import numpy as np

In [5]:
a=np.random.randint(30,99,20)
a

array([50, 61, 36, 31, 87, 43, 66, 96, 81, 48, 65, 37, 91, 90, 36, 60, 55,
       95, 67, 93])

In [6]:
a[-1]

93

In [7]:
a[4]

87

In [8]:
a.ndim

1

In [22]:
b=np.random.randint(30,99,(8,9))
b

array([[44, 94, 94, 93, 87, 38, 45, 84, 70],
       [66, 90, 98, 72, 89, 91, 95, 96, 72],
       [48, 94, 77, 61, 84, 78, 75, 45, 60],
       [49, 86, 84, 44, 59, 82, 72, 30, 84],
       [90, 84, 76, 67, 52, 91, 41, 78, 67],
       [37, 87, 46, 54, 40, 66, 51, 90, 36],
       [65, 77, 88, 67, 30, 50, 36, 40, 65],
       [92, 94, 52, 58, 52, 55, 47, 72, 88]])

In [23]:
b.shape

(8, 9)

In [24]:
b.ndim

2

In [25]:
b[7,0]

92

### array[row_start: row_end : row_step , col_start: col_end:col_step]

In [13]:
b[2:6]

array([[20, 59, 77, 74, 94, 84, 45, 43],
       [42, 61, 82, 43, 60, 57, 93, 69],
       [53, 45, 95, 98, 25, 95, 27, 65],
       [25, 27, 46, 21, 46, 87, 20, 52]])

In [26]:
b[1:5,1:6]


array([[90, 98, 72, 89, 91],
       [94, 77, 61, 84, 78],
       [86, 84, 44, 59, 82],
       [84, 76, 67, 52, 91]])

In [27]:
b[2:6:2,1:7:2]

array([[94, 61, 78],
       [84, 67, 91]])

In [28]:
import pandas as pd

In [57]:
k=[[4,7],[2,9],[7,3],[90,50]]
k


[[4, 7], [2, 9], [7, 3], [90, 50]]

In [65]:
np.array(k)

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [62]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [59]:
t.ndim

2

In [60]:
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [63]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [68]:
pd.DataFrame(k,columns=['name','sub'],index=[289,290,291,292])

name  sub
289     4    7
290     2    9
291     7    3
292    90   50

In [69]:
df['sub'].mean()

NameError: name 'df' is not defined